name: tests

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_DATABASE: messages_test
          MYSQL_USER: root
          MYSQL_PASSWORD: root
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          tools: composer:v2
          coverage: xdebug

#      - name: Setup Node
#        uses: actions/setup-node@v4
#        with:
#          node-version: '22'
#          cache: 'npm'

#      - name: Install Node Dependencies
#        run: npm ci
#
#      - name: Build Assets
#        run: npm run build

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Copy Environment File
        run: cp .env.example .env

      - name: Ajustar variables de entorno
        run: |
          sed -i 's/^DB_HOST=.*/DB_HOST=mysql/' .env
          sed -i 's/^DB_DATABASE=.*/DB_DATABASE=messages_test/' .env
          sed -i 's/^DB_USERNAME=.*/DB_USERNAME=root/' .env
          sed -i 's/^DB_PASSWORD=.*/DB_PASSWORD=root/' .env

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Tests
        run: ./vendor/bin/phpunit
